# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Navn')),
            ],
            options={
                'verbose_name': 'Afdeling',
                'verbose_name_plural': 'Afdelinger',
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Navn')),
            ],
            options={
                'verbose_name': 'Forening',
                'verbose_name_plural': 'Foreninger',
            },
        ),
    ]
