# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_department_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='union',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.Union'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.Department'),
            preserve_default=False,
        ),
    ]
