# Generated by Django 2.2.4 on 2019-08-12 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20180315_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiPasswords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=32, verbose_name='SSID')),
                ('wifi_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='WiFi Password')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='Brugernavn')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Kode')),
                ('start_dtm', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start')),
                ('end_dtm', models.DateTimeField(blank=True, null=True, verbose_name='Slut')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.Season')),
                ('seasonparticipant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.SeasonParticipant')),
            ],
            options={
                'verbose_name': 'WiFi Kode',
                'verbose_name_plural': 'WiFi Koder',
            },
        ),
    ]
