# Generated by Django 2.2.4 on 2019-09-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_wifipasswords_random_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='birthday',
        ),
    ]
