# Generated by Django 2.2.4 on 2019-09-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_remove_participants_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifipasswords',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
