# Generated by Django 2.2.4 on 2019-09-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20190903_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='members_id',
        ),
    ]
