# Generated by Django 3.2.18 on 2024-02-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_workshop_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='registered_manually',
            field=models.BooleanField(default=False, verbose_name='Registreret manuelt'),
        ),
    ]
