# Generated by Django 3.2.24 on 2024-02-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_attendance_registered_manually'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='registered_manually',
        ),
        migrations.AddField(
            model_name='attendance',
            name='registered_automatically',
            field=models.BooleanField(default=True, verbose_name='Registreret automatisk'),
        ),
    ]
