# Generated by Django 3.2.24 on 2024-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_auto_20240228_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('BC', 'Basalt'), ('MM', 'Medium'), ('SN', 'Sæson')], max_length=2, verbose_name='Præmietype')),
                ('start_date', models.DateField(verbose_name='Startdato')),
                ('end_date', models.DateField(verbose_name='Slutdato')),
                ('delivered', models.DateField(verbose_name='Leveret')),
            ],
            options={
                'verbose_name': 'Præmie',
                'verbose_name_plural': 'Præmier',
            },
        ),
        migrations.CreateModel(
            name='ClosingDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Navn')),
                ('date', models.DateField(verbose_name='Dato')),
            ],
            options={
                'verbose_name': 'Lukkedag',
                'verbose_name_plural': 'Lukkedage',
            },
        ),
    ]
