# Generated by Django 3.2.24 on 2024-04-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_awards_closingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='seasonparticipant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.seasonparticipant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closingdays',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.season'),
            preserve_default=False,
        ),
    ]
