# Generated by Django 3.2.25 on 2024-07-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_auto_20240408_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='ice',
            field=models.IntegerField(default=12, max_length=2, verbose_name='Antal gange for at tjene is'),
        ),
        migrations.AddField(
            model_name='season',
            name='merchandise',
            field=models.IntegerField(default=7, max_length=2, verbose_name='Antal gange for at tjene merch'),
        ),
        migrations.AddField(
            model_name='season',
            name='stickers',
            field=models.IntegerField(default=4, max_length=2, verbose_name='Antal gange for at tjene stickers'),
        ),
    ]
