# Generated by Django 3.2.25 on 2024-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_auto_20240726_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='ice_require_card',
            field=models.BooleanField(default=False, verbose_name='Kortet skal være brugt for at tælle for is'),
        ),
        migrations.AddField(
            model_name='season',
            name='ice_require_row',
            field=models.BooleanField(default=False, verbose_name='Gangene skal være registreret i træk for is'),
        ),
        migrations.AddField(
            model_name='season',
            name='merchandise_require_card',
            field=models.BooleanField(default=True, verbose_name='Kortet skal være brugt for at tælle for merch'),
        ),
        migrations.AddField(
            model_name='season',
            name='merchandise_require_row',
            field=models.BooleanField(default=True, verbose_name='Gangene skal være registreret i træk for merch'),
        ),
        migrations.AddField(
            model_name='season',
            name='stickers_require_card',
            field=models.BooleanField(default=False, verbose_name='Kortet skal være brugt for at tælle for stickers'),
        ),
        migrations.AddField(
            model_name='season',
            name='stickers_require_row',
            field=models.BooleanField(default=True, verbose_name='Gangene skal være registreret i træk for stickers'),
        ),
    ]
