# Generated by Django 3.2.25 on 2024-07-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_auto_20240726_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='registered_dtm',
            new_name='registered_at',
        ),
    ]
