# Generated by Django 3.2.25 on 2024-07-29 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_rename_registered_dtm_attendance_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.workshop'),
        ),
    ]
